name: petroleum_management_system
description: A Flutter application for monitoring Petroleum Management Systems in Gas Stations in Talibon, Bohol, Philippines.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  percent_indicator: ^4.2.2


  
  # UI and Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # Charts and Data Visualization
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: 29.2.7
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Utilities
  intl: ^0.20.0  # Upgraded to latest stable
  uuid: ^4.2.1
  
  # Notifications
  flutter_local_notifications: ^16.3.3
  
  # Date and Time
  table_calendar: ^3.2.0  # Upgraded to match intl
  
  # Animation
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
